In [14]:
import pandas as pd
import numpy as np

df = pd.read_excel("E:/Data Science/Datasets/assignment_data.xlsx")

In [15]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
Child name,CH_30001,CH_30002,CH_30003,CH_30004,CH_30005,CH_30006,CH_30007,CH_30008,CH_30009,CH_30010,...,CH_31431,CH_31432,CH_31433,CH_31434,CH_31435,CH_31436,CH_31437,CH_30784,CH_31438,CH_31439
phone,911100221000,911100221001,911100221002,911100221003,911100221004,911100221005,911100221006,911100221007,911100221008,911100221009,...,911100222435,911100222436,911100222437,911100222438,911100222439,911100222440,911100222441,911100222442,911100222443,911100222444
email_id,s2m_test_20001@tests2m.com,s2m_test_20002@tests2m.com,s2m_test_20003@tests2m.com,s2m_test_20004@tests2m.com,s2m_test_20005@tests2m.com,s2m_test_20006@tests2m.com,s2m_test_20007@tests2m.com,s2m_test_20008@tests2m.com,s2m_test_20009@tests2m.com,s2m_test_20010@tests2m.com,...,s2m_test_21449@tests2m.com,s2m_test_21450@tests2m.com,s2m_test_21451@tests2m.com,s2m_test_21452@tests2m.com,s2m_test_21453@tests2m.com,s2m_test_21454@tests2m.com,s2m_test_21455@tests2m.com,s2m_test_21456@tests2m.com,s2m_test_21457@tests2m.com,s2m_test_21458@tests2m.com
school,St.paul's school,K L E School haveri,Delhu Public School Howrah,Bharathi vidya bhavans,Army public school Delhi cantt,Millennium,St Paul's,Sri Sri Academy,Saint Paul's school,Shiri shiri ravishankar vidya mandir,...,"Lotus valley, Gurgaon",Kamala nikatan montessori school,Maps,St. Columbas School,Fountainhead Global School,St Paul's School,Kps,Saint Paul's school,PS Senior Secondary School,Delhi Public School panvel
grade,Grade 2,Grade 4,Grade 2,Grade 2,Grade 4,Grade 1,Grade 4,Grade 4,Grade 4,Grade 1,...,Grade 3,Grade 4,Grade 2,Grade 4,Grade 4,Grade 2,Grade 2,Grade 3,Grade 4,Grade 2
batch_preferred,"Afternoon Batch (4:00 - 4:45 PM), Evening Batc...","Evening Batch (6:15 - 7:00 PM), Morning Batch ...","Morning Batch (11:15 - 12:00 PM), Evening Batc...","Evening Batch (6:15 - 7:00 PM), Afternoon Batc...","Evening Batch (6:15 - 7:00 PM), Afternoon Batc...","Morning Batch (11:15 - 12:00 PM), Afternoon Ba...","Morning Batch (11:15 - 12:00 PM), Afternoon Ba...","Afternoon Batch (4:00 - 4:45 PM), Evening Batc...","Evening Batch (6:15 - 7:00 PM), Morning Batch ...","Evening Batch (6:15 - 7:00 PM), Afternoon Batc...",...,"Evening Batch (6:00 - 6:45 PM), Morning Batch ...","Evening Batch (6:00 - 6:45 PM), Morning Batch ...","Evening Batch (6:00 - 6:45 PM), Morning Batch ...","Evening Batch (6:00 - 6:45 PM), Morning Batch ...","Morning Batch (11:45 - 12:30 PM), Evening Batc...","Morning Batch (11:45 - 12:30 PM), Evening Batc...","Evening Batch (6:00 - 6:45 PM), Morning Batch ...","Morning Batch (11:45 - 12:30 PM), Evening Batc...","Morning Batch (11:45 - 12:30 PM), Evening Batc...","Evening Batch (6:00 - 6:45 PM), Morning Batch ..."
source,lastchance,lastchance,lastchance,lastchance,lastchance,lastchance,lastchance,lastchance,lastchance,lastchance,...,adarsh,b3rmsms,marchhiusms,marchhiusms,marchhiusms,marchhiusms,marchhiusms,marchhiusms,marchhiusms,b3rmsms
Submitted At,2020-04-16 08:46:39,2020-04-16 08:47:55,2020-04-16 08:47:59,2020-04-16 08:48:27,2020-04-16 08:52:06,2020-04-16 08:52:12,2020-04-16 08:53:13,2020-04-16 08:53:18,2020-04-16 08:55:41,2020-04-16 08:55:48,...,2020-04-27 14:47:00,2020-04-27 14:47:41,2020-04-27 15:00:24,2020-04-27 15:14:43,2020-04-27 15:23:42,2020-04-27 16:22:16,2020-04-27 16:39:31,2020-04-27 17:26:57,2020-04-27 17:35:25,2020-04-27 18:33:02

In [16]:
df.isna().sum()

Child name         0
phone              0
email_id           0
school             0
grade              0
batch_preferred    0
source             2
Submitted At       0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1683 entries, 0 to 1682
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Child name       1683 non-null   object
 1   phone            1683 non-null   int64
 2   email_id         1683 non-null   object
 3   school           1683 non-null   object
 4   grade            1683 non-null   object
 5   batch_preferred  1683 non-null   object
 6   source           1681 non-null   object
 7   Submitted At     1683 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 105.3+ KB

In [18]:
df.nunique()

Child name         1439
phone              1445
email_id           1458
school             1107
grade                 4
batch_preferred       8
source               23
Submitted At       1668
dtype: int64